name: build-controller-image

on:
  push:
    branches: ["local"]
    paths:
      - "controller/**"
      - ".github/workflows/build-controller-image.yaml"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner
        id: owner
        run: echo "name=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./controller
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/home-monitoring/controller:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/home-monitoring/controller:local